const agents = [
  { id: 1, name: "Elena Martínez", role: { es: "Directora Comercial", en: "Sales Director", de: "Vertriebsleiterin", fr: "Directrice Commerciale" }, phone: "+34 612 345 678", email: "elena@inmobiliariaprueba.es", photo: "https://picsum.photos/seed/agent1/200/200", bio: { es: "15 años de experiencia en el mercado inmobiliario de lujo.", en: "15 years of experience in the luxury real estate market." } },
  { id: 2, name: "Carlos Ruiz", role: { es: "Asesor Senior", en: "Senior Advisor", de: "Senior-Berater", fr: "Conseiller Senior" }, phone: "+34 623 456 789", email: "carlos@inmobiliariaprueba.es", photo: "https://picsum.photos/seed/agent2/200/200", bio: { es: "Especialista en propiedades de alto standing y obra nueva.", en: "Specialist in high-end and new-build properties." } },
  { id: 3, name: "Sofía Delgado", role: { es: "Asesora Residencial", en: "Residential Advisor", de: "Wohnberaterin", fr: "Conseillère Résidentielle" }, phone: "+34 634 567 890", email: "sofia@inmobiliariaprueba.es", photo: "https://picsum.photos/seed/agent3/200/200", bio: { es: "Experta en el mercado de alquiler premium y gestión de activos.", en: "Expert in premium rental market and asset management." } },
];

const properties = [
  {
    id: 1,
    title: { es: "Ático con terraza panorámica en Salamanca", en: "Penthouse with panoramic terrace in Salamanca", de: "Dachterrassenwohnung mit Panoramablick in Salamanca", fr: "Penthouse avec terrasse panoramique à Salamanque" },
    type: "venta",
    category: "piso",
    price: 1250000,
    m2: 185,
    m2Terrace: 45,
    bedrooms: 4,
    bathrooms: 3,
    floor: 8,
    totalFloors: 8,
    elevator: true,
    garage: 2,
    storage: true,
    yearBuilt: 2019,
    energyCert: "A",
    address: { es: "Calle Serrano 89, Madrid", en: "89 Serrano Street, Madrid", de: "Serrano Straße 89, Madrid", fr: "89 Rue Serrano, Madrid" },
    neighbourhood: "Salamanca",
    city: "Madrid",
    coords: [40.4269, -3.6854],
    photos: [
      "https://picsum.photos/seed/p1a/1200/800",
      "https://picsum.photos/seed/p1b/1200/800",
      "https://picsum.photos/seed/p1c/1200/800",
      "https://picsum.photos/seed/p1d/1200/800",
      "https://picsum.photos/seed/p1e/1200/800",
      "https://picsum.photos/seed/p1f/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Ático+185m²",
    featured: true,
    description: {
      es: "Espectacular ático de diseño exclusivo en el corazón del barrio de Salamanca. Con una superficie construida de 185m² y una terraza privada de 45m² con vistas panorámicas a la ciudad. Completamente reformado con materiales de primera calidad: suelos de mármol italiano, cocina Santos equipada con electrodomésticos Gaggenau, y carpintería de aluminio de rotura de puente térmico. Dos plazas de garaje y trastero incluidos.",
      en: "Spectacular designer penthouse in the heart of the Salamanca district. With a built area of 185m² and a private terrace of 45m² with panoramic city views. Completely renovated with top quality materials: Italian marble floors, Santos kitchen equipped with Gaggenau appliances, and thermal break aluminum carpentry. Two parking spaces and storage room included.",
      de: "Spektakuläres Design-Penthouse im Herzen des Stadtviertels Salamanca. Mit einer Wohnfläche von 185m² und einer privaten Terrasse von 45m² mit Panoramablick auf die Stadt.",
      fr: "Spectaculaire penthouse de design exclusif au cœur du quartier Salamanca. Avec une surface construite de 185m² et une terrasse privée de 45m² avec vue panoramique."
    },
    agent: 1,
    visits: 847,
    priceHistory: [1100000, 1150000, 1180000, 1220000, 1250000],
    tags: ["terraza", "reformado", "vistas", "lujo", "garaje"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Metro Serrano", en: "Serrano Metro" }, type: "metro", distance: "120m", coords: [40.4279, -3.6864] },
      { name: { es: "Colegio Alemán", en: "German School" }, type: "school", distance: "350m", coords: [40.4285, -3.6840] },
      { name: { es: "El Corte Inglés Serrano", en: "El Corte Inglés Serrano" }, type: "shopping", distance: "200m", coords: [40.4260, -3.6870] },
      { name: { es: "Parque del Retiro", en: "Retiro Park" }, type: "park", distance: "800m", coords: [40.4153, -3.6844] }
    ]
  },
  {
    id: 2,
    title: { es: "Piso de lujo en primera línea de playa", en: "Luxury apartment on the beachfront", de: "Luxuswohnung in erster Meeresreihe", fr: "Appartement de luxe en bord de mer" },
    type: "venta",
    category: "piso",
    price: 890000,
    m2: 145,
    m2Terrace: 25,
    bedrooms: 3,
    bathrooms: 2,
    floor: 4,
    totalFloors: 6,
    elevator: true,
    garage: 1,
    storage: false,
    yearBuilt: 2021,
    energyCert: "B",
    address: { es: "Paseo Marítimo 45, Marbella", en: "45 Seafront Promenade, Marbella", de: "Strandpromenade 45, Marbella", fr: "45 Promenade du Bord de Mer, Marbella" },
    neighbourhood: "Nueva Andalucía",
    city: "Marbella",
    coords: [36.5100, -4.8852],
    photos: [
      "https://picsum.photos/seed/p2a/1200/800",
      "https://picsum.photos/seed/p2b/1200/800",
      "https://picsum.photos/seed/p2c/1200/800",
      "https://picsum.photos/seed/p2d/1200/800",
      "https://picsum.photos/seed/p2e/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+145m²",
    featured: true,
    description: {
      es: "Impresionante piso en primera línea de playa en Marbella. Vistas directas al mar Mediterráneo desde todas las habitaciones. Amplia terraza con jacuzzi exterior. Acabados de lujo con suelos de porcelana italiana y cocina abierta al salón.",
      en: "Impressive first-line beach apartment in Marbella. Direct Mediterranean sea views from all rooms. Large terrace with outdoor jacuzzi. Luxury finishes with Italian porcelain floors and open kitchen.",
      de: "Beeindruckende Strandwohnung in erster Reihe in Marbella. Direkter Meerblick aus allen Zimmern. Große Terrasse mit Außenwhirlpool.",
      fr: "Impressionnant appartement en première ligne de plage à Marbella. Vue directe sur la mer Méditerranée depuis toutes les pièces."
    },
    agent: 2,
    visits: 1203,
    priceHistory: [820000, 845000, 860000, 875000, 890000],
    tags: ["primera línea", "vistas al mar", "terraza", "jacuzzi"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Playa+145m²",
    poi: [
      { name: { es: "Playa Venus", en: "Venus Beach" }, type: "park", distance: "50m", coords: [36.5095, -4.8860] },
      { name: { es: "Puerto Banús", en: "Puerto Banús" }, type: "shopping", distance: "2km", coords: [36.4930, -4.9534] }
    ]
  },
  {
    id: 3,
    title: { es: "Villa con piscina en La Moraleja", en: "Villa with pool in La Moraleja", de: "Villa mit Pool in La Moraleja", fr: "Villa avec piscine à La Moraleja" },
    type: "venta",
    category: "villa",
    price: 2800000,
    m2: 520,
    m2Garden: 1200,
    bedrooms: 6,
    bathrooms: 5,
    floor: 0,
    totalFloors: 2,
    elevator: false,
    garage: 3,
    storage: true,
    yearBuilt: 2015,
    energyCert: "C",
    address: { es: "Av. de Europa 12, La Moraleja, Alcobendas", en: "12 Europa Avenue, La Moraleja, Alcobendas", de: "Europa Allee 12, La Moraleja, Alcobendas", fr: "12 Avenue d'Europe, La Moraleja, Alcobendas" },
    neighbourhood: "La Moraleja",
    city: "Madrid",
    coords: [40.5218, -3.6494],
    photos: [
      "https://picsum.photos/seed/p3a/1200/800",
      "https://picsum.photos/seed/p3b/1200/800",
      "https://picsum.photos/seed/p3c/1200/800",
      "https://picsum.photos/seed/p3d/1200/800",
      "https://picsum.photos/seed/p3e/1200/800",
      "https://picsum.photos/seed/p3f/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Villa+520m²",
    featured: true,
    description: {
      es: "Excepcional villa de estilo contemporáneo en la exclusiva urbanización de La Moraleja. Distribuida en tres plantas con amplios espacios luminosos, jardín privado con piscina y zona de barbacoa, y garaje para tres vehículos. Domótica integrada, sistema de seguridad 24h y energía solar.",
      en: "Exceptional contemporary style villa in the exclusive La Moraleja development. Spread over three floors with large bright spaces, private garden with pool and barbecue area, and garage for three vehicles. Integrated home automation, 24h security system and solar energy.",
      de: "Außergewöhnliche Villa im zeitgenössischen Stil in der exklusiven Siedlung La Moraleja. Verteilt auf drei Etagen mit großen hellen Räumen, privatem Garten mit Pool.",
      fr: "Villa exceptionnelle de style contemporain dans la résidence exclusive de La Moraleja. Répartie sur trois étages avec de grands espaces lumineux, jardin privé avec piscine."
    },
    agent: 1,
    visits: 432,
    priceHistory: [2500000, 2600000, 2700000, 2750000, 2800000],
    tags: ["villa", "piscina", "jardín", "domótica", "lujo"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Golf La Moraleja", en: "La Moraleja Golf" }, type: "park", distance: "500m", coords: [40.5250, -3.6520] },
      { name: { es: "Colegio El Prado", en: "El Prado School" }, type: "school", distance: "800m", coords: [40.5180, -3.6450] }
    ]
  },
  {
    id: 4,
    title: { es: "Piso moderno en el Eixample de Barcelona", en: "Modern apartment in Barcelona's Eixample", de: "Moderne Wohnung im Eixample von Barcelona", fr: "Appartement moderne dans l'Eixample de Barcelone" },
    type: "venta",
    category: "piso",
    price: 685000,
    m2: 110,
    bedrooms: 3,
    bathrooms: 2,
    floor: 3,
    totalFloors: 7,
    elevator: true,
    garage: 0,
    storage: true,
    yearBuilt: 1920,
    energyCert: "D",
    address: { es: "Passeig de Gràcia 78, Barcelona", en: "78 Passeig de Gràcia, Barcelona", de: "Passeig de Gràcia 78, Barcelona", fr: "78 Passeig de Gràcia, Barcelone" },
    neighbourhood: "Eixample",
    city: "Barcelona",
    coords: [41.3925, 2.1644],
    photos: [
      "https://picsum.photos/seed/p4a/1200/800",
      "https://picsum.photos/seed/p4b/1200/800",
      "https://picsum.photos/seed/p4c/1200/800",
      "https://picsum.photos/seed/p4d/1200/800",
      "https://picsum.photos/seed/p4e/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Eixample+110m²",
    featured: false,
    description: {
      es: "Elegante piso en un edificio modernista en el corazón del Eixample barcelonés. Techos altos con molduras originales restauradas, suelos de mosaico hidráulico y grandes ventanales a Passeig de Gràcia. Completamente reformado respetando los elementos arquitectónicos originales.",
      en: "Elegant apartment in a modernist building in the heart of Barcelona's Eixample. High ceilings with restored original moldings, hydraulic mosaic floors and large windows onto Passeig de Gràcia. Fully renovated respecting original architectural elements.",
      de: "Elegante Wohnung in einem modernistischen Gebäude im Herzen des Eixample in Barcelona. Hohe Decken mit restaurierten Originalstuckarbeiten.",
      fr: "Élégant appartement dans un immeuble moderniste au cœur de l'Eixample barcelonais."
    },
    agent: 2,
    visits: 567,
    priceHistory: [620000, 640000, 655000, 670000, 685000],
    tags: ["modernista", "techos altos", "reformado", "céntrico"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Casa Batlló", en: "Casa Batlló" }, type: "park", distance: "200m", coords: [41.3916, 2.1650] },
      { name: { es: "Metro Passeig de Gràcia", en: "Passeig de Gràcia Metro" }, type: "metro", distance: "80m", coords: [41.3921, 2.1651] }
    ]
  },
  {
    id: 5,
    title: { es: "Apartamento en alquiler en Malasaña", en: "Apartment for rent in Malasaña", de: "Wohnung zur Miete in Malasaña", fr: "Appartement à louer à Malasaña" },
    type: "alquiler",
    category: "piso",
    price: 1850,
    m2: 75,
    bedrooms: 2,
    bathrooms: 1,
    floor: 2,
    totalFloors: 5,
    elevator: false,
    garage: 0,
    storage: false,
    yearBuilt: 1975,
    energyCert: "E",
    address: { es: "Calle Fuencarral 102, Madrid", en: "102 Fuencarral Street, Madrid", de: "Fuencarral Straße 102, Madrid", fr: "102 Rue Fuencarral, Madrid" },
    neighbourhood: "Malasaña",
    city: "Madrid",
    coords: [40.4244, -3.7038],
    photos: [
      "https://picsum.photos/seed/p5a/1200/800",
      "https://picsum.photos/seed/p5b/1200/800",
      "https://picsum.photos/seed/p5c/1200/800",
      "https://picsum.photos/seed/p5d/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Malasaña+75m²",
    featured: false,
    description: {
      es: "Acogedor apartamento completamente reformado en el vibrante barrio de Malasaña. Cocina abierta al salón, dormitorio principal con vestidor y baño completo con bañera. Suelos de madera natural y ventanas de doble acristalamiento.",
      en: "Cozy fully renovated apartment in the vibrant Malasaña neighborhood. Open kitchen to living room, master bedroom with walk-in closet and full bathroom with bathtub. Natural wood floors and double glazed windows.",
      de: "Gemütliche, vollständig renovierte Wohnung im lebhaften Viertel Malasaña.",
      fr: "Appartement chaleureux entièrement rénové dans le quartier vivant de Malasaña."
    },
    agent: 3,
    visits: 389,
    priceHistory: [1600, 1680, 1720, 1780, 1850],
    tags: ["reformado", "madera", "luminoso", "céntrico"],
    videoUrl: null,
    poi: [
      { name: { es: "Metro Bilbao", en: "Bilbao Metro" }, type: "metro", distance: "200m", coords: [40.4262, -3.7021] },
      { name: { es: "Mercado San Antón", en: "San Antón Market" }, type: "shopping", distance: "400m", coords: [40.4230, -3.6990] }
    ]
  },
  {
    id: 6,
    title: { es: "Estudio de diseño en el Born, Barcelona", en: "Design studio in El Born, Barcelona", de: "Design-Studio im Born, Barcelona", fr: "Studio design dans le Born, Barcelone" },
    type: "alquiler",
    category: "piso",
    price: 1200,
    m2: 45,
    bedrooms: 0,
    bathrooms: 1,
    floor: 1,
    totalFloors: 4,
    elevator: false,
    garage: 0,
    storage: false,
    yearBuilt: 1890,
    energyCert: "F",
    address: { es: "Carrer del Parlament 23, Barcelona", en: "23 Parlament Street, Barcelona", de: "Parlament Straße 23, Barcelona", fr: "23 Rue Parlament, Barcelone" },
    neighbourhood: "El Born",
    city: "Barcelona",
    coords: [41.3844, 2.1823],
    photos: [
      "https://picsum.photos/seed/p6a/1200/800",
      "https://picsum.photos/seed/p6b/1200/800",
      "https://picsum.photos/seed/p6c/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Studio+45m²",
    featured: false,
    description: {
      es: "Luminoso estudio de diseño en el corazón del barrio del Born. Techos de 3,5m con vigas de madera originales. Totalmente equipado, ideal para jóvenes profesionales o parejas. Acceso a terraza comunitaria en azotea.",
      en: "Bright design studio in the heart of El Born. 3.5m ceilings with original wooden beams. Fully equipped, ideal for young professionals or couples. Access to communal rooftop terrace.",
      de: "Helles Design-Studio im Herzen des Born-Viertels. 3,5m hohe Decken mit originalen Holzbalken.",
      fr: "Studio design lumineux au cœur du quartier du Born. Plafonds de 3,5m avec des poutres en bois originales."
    },
    agent: 3,
    visits: 512,
    priceHistory: [1000, 1050, 1100, 1150, 1200],
    tags: ["diseño", "techos altos", "Born", "terrace"],
    videoUrl: null,
    poi: [
      { name: { es: "Mercat de Santa Caterina", en: "Santa Caterina Market" }, type: "shopping", distance: "300m", coords: [41.3858, 2.1773] },
      { name: { es: "Parque de la Ciutadella", en: "Ciutadella Park" }, type: "park", distance: "600m", coords: [41.3860, 2.1865] }
    ]
  },
  {
    id: 7,
    title: { es: "Casa adosada con jardín en Pozuelo", en: "Townhouse with garden in Pozuelo", de: "Reihenhaus mit Garten in Pozuelo", fr: "Maison de ville avec jardin à Pozuelo" },
    type: "venta",
    category: "casa",
    price: 495000,
    m2: 210,
    m2Garden: 80,
    bedrooms: 4,
    bathrooms: 3,
    floor: 0,
    totalFloors: 3,
    elevator: false,
    garage: 1,
    storage: true,
    yearBuilt: 2008,
    energyCert: "C",
    address: { es: "Calle Pradillo 15, Pozuelo de Alarcón", en: "15 Pradillo Street, Pozuelo de Alarcón", de: "Pradillo Straße 15, Pozuelo de Alarcón", fr: "15 Rue Pradillo, Pozuelo de Alarcón" },
    neighbourhood: "El Cantizal",
    city: "Pozuelo de Alarcón",
    coords: [40.4462, -3.7935],
    photos: [
      "https://picsum.photos/seed/p7a/1200/800",
      "https://picsum.photos/seed/p7b/1200/800",
      "https://picsum.photos/seed/p7c/1200/800",
      "https://picsum.photos/seed/p7d/1200/800",
      "https://picsum.photos/seed/p7e/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Adosado+210m²",
    featured: false,
    description: {
      es: "Luminosa casa adosada en urbanización privada con vigilancia 24h en Pozuelo de Alarcón. Salón-comedor con salida directa al jardín privado, cocina americana, 4 dormitorios con armarios empotrados y 3 baños completos. Garaje individual y trastero.",
      en: "Bright townhouse in private gated development with 24h security in Pozuelo de Alarcón. Living-dining room with direct access to private garden, open kitchen, 4 bedrooms with built-in wardrobes and 3 full bathrooms. Individual garage and storage room.",
      de: "Helles Reihenhaus in einer privaten, überwachten Siedlung in Pozuelo de Alarcón.",
      fr: "Maison de ville lumineuse dans une résidence privée gardée 24h à Pozuelo de Alarcón."
    },
    agent: 2,
    visits: 298,
    priceHistory: [450000, 465000, 475000, 485000, 495000],
    tags: ["adosado", "jardín", "urbanización", "vigilancia"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Colegio El Prado", en: "El Prado School" }, type: "school", distance: "600m", coords: [40.4490, -3.7900] },
      { name: { es: "Centro Comercial Pozuelo", en: "Pozuelo Shopping Center" }, type: "shopping", distance: "1.2km", coords: [40.4420, -3.7870] }
    ]
  },
  {
    id: 8,
    title: { es: "Piso reformado en Gracia, Barcelona", en: "Renovated apartment in Gracia, Barcelona", de: "Renovierte Wohnung in Gracia, Barcelona", fr: "Appartement rénové à Gracia, Barcelone" },
    type: "venta",
    category: "piso",
    price: 420000,
    m2: 90,
    bedrooms: 3,
    bathrooms: 2,
    floor: 4,
    totalFloors: 5,
    elevator: true,
    garage: 0,
    storage: false,
    yearBuilt: 1965,
    energyCert: "D",
    address: { es: "Carrer de Verdi 56, Barcelona", en: "56 Verdi Street, Barcelona", de: "Verdi Straße 56, Barcelona", fr: "56 Rue Verdi, Barcelone" },
    neighbourhood: "Gracia",
    city: "Barcelona",
    coords: [41.4035, 2.1574],
    photos: [
      "https://picsum.photos/seed/p8a/1200/800",
      "https://picsum.photos/seed/p8b/1200/800",
      "https://picsum.photos/seed/p8c/1200/800",
      "https://picsum.photos/seed/p8d/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Gracia+90m²",
    featured: false,
    description: {
      es: "Precioso piso totalmente reformado en el emblemático barrio de Gracia. Distribución inteligente con tres habitaciones, cocina integrada con office y dos baños con ducha de obra. Suelos de parquet de roble y ventanas de madera lacada.",
      en: "Beautiful fully renovated apartment in the iconic Gracia neighborhood. Smart layout with three bedrooms, integrated kitchen with dining area and two tiled shower bathrooms. Oak parquet floors and lacquered wood windows.",
      de: "Wunderschöne, vollständig renovierte Wohnung im ikonischen Viertel Gracia.",
      fr: "Bel appartement entièrement rénové dans l'emblématique quartier de Gracia."
    },
    agent: 3,
    visits: 445,
    priceHistory: [380000, 390000, 400000, 410000, 420000],
    tags: ["reformado", "parquet", "luminoso", "Gracia"],
    videoUrl: null,
    poi: [
      { name: { es: "Parque Güell", en: "Güell Park" }, type: "park", distance: "800m", coords: [41.4145, 2.1527] },
      { name: { es: "Metro Fontana", en: "Fontana Metro" }, type: "metro", distance: "150m", coords: [41.4025, 2.1571] }
    ]
  },
  {
    id: 9,
    title: { es: "Apartamento de obra nueva en Valencia", en: "New-build apartment in Valencia", de: "Neubau-Wohnung in Valencia", fr: "Appartement neuf à Valence" },
    type: "venta",
    category: "piso",
    price: 310000,
    m2: 95,
    m2Terrace: 12,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    totalFloors: 10,
    elevator: true,
    garage: 1,
    storage: true,
    yearBuilt: 2024,
    energyCert: "A",
    address: { es: "Av. del Puerto 34, Valencia", en: "34 Puerto Avenue, Valencia", de: "Puerto Allee 34, Valencia", fr: "34 Avenue du Port, Valence" },
    neighbourhood: "El Cabanyal",
    city: "Valencia",
    coords: [39.4699, -0.3773],
    photos: [
      "https://picsum.photos/seed/p9a/1200/800",
      "https://picsum.photos/seed/p9b/1200/800",
      "https://picsum.photos/seed/p9c/1200/800",
      "https://picsum.photos/seed/p9d/1200/800",
      "https://picsum.photos/seed/p9e/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Obra+Nueva+95m²",
    featured: false,
    description: {
      es: "Moderno apartamento de obra nueva en la zona del Puerto de Valencia con terraza privada. Calificación energética A con aerotermia, paneles solares y sistema de recuperación de calor. Cocina con isla, baños con pavimento porcelánico gran formato y amplias ventanas.",
      en: "Modern new-build apartment near Valencia's port area with private terrace. Energy rating A with aerothermal heating, solar panels and heat recovery system. Kitchen with island, bathrooms with large-format porcelain tiles and large windows.",
      de: "Moderne Neubau-Wohnung in der Hafengegend von Valencia mit privater Terrasse.",
      fr: "Appartement neuf moderne près du port de Valence avec terrasse privée."
    },
    agent: 1,
    visits: 623,
    priceHistory: [290000, 295000, 300000, 305000, 310000],
    tags: ["obra nueva", "eficiencia energética", "aerotermia", "garaje"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Playa de la Malvarrosa", en: "Malvarrosa Beach" }, type: "park", distance: "400m", coords: [39.4745, -0.3320] },
      { name: { es: "Mercado Central", en: "Central Market" }, type: "shopping", distance: "3km", coords: [39.4737, -0.3788] }
    ]
  },
  {
    id: 10,
    title: { es: "Local comercial en zona prime, Madrid", en: "Prime commercial space in Madrid", de: "Erstklassige Gewerbeimmobilie in Madrid", fr: "Local commercial en zone prime, Madrid" },
    type: "alquiler",
    category: "local",
    price: 4500,
    m2: 180,
    bedrooms: 0,
    bathrooms: 2,
    floor: 0,
    totalFloors: 1,
    elevator: false,
    garage: 0,
    storage: true,
    yearBuilt: 1995,
    energyCert: "C",
    address: { es: "Calle Alcalá 45, Madrid", en: "45 Alcalá Street, Madrid", de: "Alcalá Straße 45, Madrid", fr: "45 Rue Alcalá, Madrid" },
    neighbourhood: "Retiro",
    city: "Madrid",
    coords: [40.4186, -3.6969],
    photos: [
      "https://picsum.photos/seed/p10a/1200/800",
      "https://picsum.photos/seed/p10b/1200/800",
      "https://picsum.photos/seed/p10c/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Local+180m²",
    featured: false,
    description: {
      es: "Amplio local comercial en planta baja en una de las arterias principales de Madrid. Escaparate de gran visibilidad, dos aseos, almacén y zona de office. Ideal para restauración, tienda de moda o showroom de lujo.",
      en: "Large ground floor commercial space on one of Madrid's main arteries. Large display window, two bathrooms, storage and office area. Ideal for restaurant, fashion store or luxury showroom.",
      de: "Großes Erdgeschoss-Gewerbelokal in einer der Hauptstraßen Madrids.",
      fr: "Grand local commercial au rez-de-chaussée dans l'une des artères principales de Madrid."
    },
    agent: 2,
    visits: 187,
    priceHistory: [4000, 4100, 4200, 4350, 4500],
    tags: ["local", "prime", "escaparate", "hostelería"],
    videoUrl: null,
    poi: [
      { name: { es: "Metro Retiro", en: "Retiro Metro" }, type: "metro", distance: "100m", coords: [40.4178, -3.6956] },
      { name: { es: "Parque del Retiro", en: "Retiro Park" }, type: "park", distance: "300m", coords: [40.4153, -3.6844] }
    ]
  },
  {
    id: 11,
    title: { es: "Chalet independiente en Sierra de Madrid", en: "Detached house in Sierra de Madrid", de: "Freistehendes Haus in der Sierra de Madrid", fr: "Chalet indépendant à Sierra de Madrid" },
    type: "venta",
    category: "casa",
    price: 750000,
    m2: 320,
    m2Garden: 800,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    totalFloors: 2,
    elevator: false,
    garage: 2,
    storage: true,
    yearBuilt: 2001,
    energyCert: "D",
    address: { es: "Camino de la Sierra 8, Cercedilla", en: "8 Mountain Path, Cercedilla", de: "Bergweg 8, Cercedilla", fr: "8 Chemin de la Sierra, Cercedilla" },
    neighbourhood: "Cercedilla",
    city: "Cercedilla",
    coords: [40.7352, -4.0514],
    photos: [
      "https://picsum.photos/seed/p11a/1200/800",
      "https://picsum.photos/seed/p11b/1200/800",
      "https://picsum.photos/seed/p11c/1200/800",
      "https://picsum.photos/seed/p11d/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Chalet+320m²",
    featured: false,
    description: {
      es: "Majestuoso chalet en plena Sierra de Madrid rodeado de pinos centenarios. Salón con chimenea, cocina rural, 5 dormitorios con baños en suite, piscina climatizada exterior y garaje para dos coches. Tranquilidad y naturaleza a 50 minutos de Madrid capital.",
      en: "Majestic chalet in the heart of Sierra de Madrid surrounded by century-old pines. Living room with fireplace, country kitchen, 5 en-suite bedrooms, outdoor heated pool and two-car garage. Peace and nature 50 minutes from Madrid city center.",
      de: "Majestätisches Chalet mitten in der Sierra de Madrid, umgeben von jahrhundertealten Kiefern.",
      fr: "Majestueux chalet au cœur de la Sierra de Madrid entouré de pins centenaires."
    },
    agent: 1,
    visits: 234,
    priceHistory: [680000, 700000, 720000, 735000, 750000],
    tags: ["sierra", "piscina", "chimenea", "naturaleza", "tranquilidad"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Estación de tren Cercedilla", en: "Cercedilla Train Station" }, type: "metro", distance: "1.2km", coords: [40.7320, -4.0490] },
      { name: { es: "Monte Siete Picos", en: "Siete Picos Mountain" }, type: "park", distance: "2km", coords: [40.7480, -4.0350] }
    ]
  },
  {
    id: 12,
    title: { es: "Penthouse con vistas al Mediterráneo, Valencia", en: "Penthouse with Mediterranean views, Valencia", de: "Penthouse mit Mittelmeerblick, Valencia", fr: "Penthouse avec vue Méditerranée, Valence" },
    type: "venta",
    category: "piso",
    price: 580000,
    m2: 140,
    m2Terrace: 60,
    bedrooms: 3,
    bathrooms: 2,
    floor: 12,
    totalFloors: 12,
    elevator: true,
    garage: 1,
    storage: true,
    yearBuilt: 2022,
    energyCert: "B",
    address: { es: "Av. de Francia 22, Valencia", en: "22 Francia Avenue, Valencia", de: "Francia Allee 22, Valencia", fr: "22 Avenue de France, Valence" },
    neighbourhood: "Ciudad de las Artes",
    city: "Valencia",
    coords: [39.4570, -0.3505],
    photos: [
      "https://picsum.photos/seed/p12a/1200/800",
      "https://picsum.photos/seed/p12b/1200/800",
      "https://picsum.photos/seed/p12c/1200/800",
      "https://picsum.photos/seed/p12d/1200/800",
      "https://picsum.photos/seed/p12e/1200/800"
    ],
    floorPlan: "https://placehold.co/600x400/E2DDD6/1C3A2F?text=Plano+Penthouse+140m²",
    featured: true,
    description: {
      es: "Exclusivo penthouse con vistas de 360° al Mediterráneo y a la Ciudad de las Artes y las Ciencias. Terraza perimetral de 60m² con jacuzzi. Interior de diseño contemporáneo con cocina Boffi, suelos de microcemento pulido y sistema de domótica KNX. Un inmueble único en Valencia.",
      en: "Exclusive penthouse with 360° views over the Mediterranean and the City of Arts and Sciences. 60m² perimeter terrace with jacuzzi. Contemporary design interior with Boffi kitchen, polished microcement floors and KNX home automation. A unique property in Valencia.",
      de: "Exklusives Penthouse mit 360°-Blick aufs Mittelmeer und die Stadt der Künste und Wissenschaften.",
      fr: "Penthouse exclusif avec vues à 360° sur la Méditerranée et la Cité des Arts et des Sciences."
    },
    agent: 2,
    visits: 789,
    priceHistory: [520000, 540000, 555000, 568000, 580000],
    tags: ["penthouse", "vistas", "jacuzzi", "diseño", "valencia"],
    videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ",
    poi: [
      { name: { es: "Ciudad de las Artes y Ciencias", en: "City of Arts and Sciences" }, type: "park", distance: "300m", coords: [39.4546, -0.3514] },
      { name: { es: "Playa El Saler", en: "El Saler Beach" }, type: "park", distance: "5km", coords: [39.4150, -0.3350] }
    ]
  },
];

if (typeof module !== 'undefined') module.exports = { properties, agents };
